### ISSUE TITLE
EDScout

### ISSUE THREAD

**Issue by Vlodec** [joncage/ed-scout#105]
You may recall our conversation on YouTube 3 days ago. Typically, it worked fine for a couple of days. Then started playing up again.......

[EDScout-2020-10-03-09-52-59.log](https://github.com/joncage/ed-scout/files/5321415/EDScout-2020-10-03-09-52-59.log)

Have fun.

**Comment by joncage** [comment]
Some more questions for you when you have a sec..

* What filesystem do you use? (NTFS? Fat32? Something else?)
* What version if Windows?
* What other tools do you run in parallel?
* What order do you normally start EDScout, Elite and any other tools?

**Comment by lauhayden** [comment]
I just experienced this issue myself. This kept happening across several restarts of Elite + EDScout. The thing that fixed it for me was right-click (on main GUI) -> Refresh. Perhaps it's a caching issue?

**Comment by Vlodec** [comment]
What do you mean by "on main GUI"? I tried "Reload" on EDScout and that doesn't seem to fix it.

**Comment by BinaryEnigma01** [comment]
This is my only problem with this great program, it seems like it simply will not try to refresh for me when the game is already loaded, sometimes even when the program started before Elite, restarting both and sometimes windows "fixes" it

* Reloading the program does not fix it (via right-click, Reload)
* Replotting the route does not fix it (although the log reports FSDTarget event
* Restarting the program by closing the background task on Task Manager does not work (Log still says `Found existing Scout instance PID:`{process ID, varies}`, killing off before continuing`, so please tell me how to properly close it)
* Using the "remote connection" yields the same results

I'm using version 1.7.1 on Windows 10

**Comment by KingGLEB** [comment]
The program worked yesterday, but today it does not. Didn't do anything, just started it. Restarting doesn't help. It writes events to the log, but there is no information in the browser.

**Comment by tautomer** [comment]
> The program worked yesterday, but today it does not. Didn't do anything, just started it. Restarting doesn't help. It writes events to the log, but there is no information in the browser.

Same to me. Stuck at "WAITING FOR NAV DATA" forever today. It was working fine yesterday.

**Comment by SethMurrow** [comment]
Sticks on "WAITING FOR NAV DATA"
Persists through reboots and uninstalling & reinstalling.
Log files appear to show data being read from journal, however nothing propagates to "GUI"
Seemed to start as an intermittent problem that would go away by restarting ED Scout or restarting the game.
"Found existing Scout instance PID:{process ID, varies}, killing off before continuing" often shows in logs.

Current readout from DiagnosticBuild:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "EDScoutWebUI\EDScout.py", line 173, in receive_and_forward
  File "EDScoutCore\EDScout.py", line 47, in trigger_current_journal_check
  File "EDScoutCore\JournalInterface.py", line 189, in trigger_current_journal_check
  File "EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
  File "EDScoutCore\EDScout.py", line 168, in on_journal_change
  File "EDScoutCore\EDScout.py", line 174, in process_new_journal_entries
  File "EDScoutCore\EDScout.py", line 143, in process_journal_change
  File "EDScoutCore\EDScout.py", line 204, in on_new_route
  File "EDScoutCore\EDScout.py", line 181, in get_edsm_system_report
  File "EDScoutCore\EDSMInterface.py", line 72, in get_system_estimated_value
TypeError: exceptions must derive from BaseException

Current Log file:
2021-01-12T01:45:52.733Z - EDScoutWebUI-EDScout - INFO - ED Scout v1.7.1 Starting
2021-01-12T01:45:53.255Z - EDScoutWebUI-EDScout - INFO - Looking for HUD overrides in C:\Users\chill\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\GraphicsConfigurationOverride.xml
2021-01-12T01:45:53.257Z - EDScoutWebUI-EDScout - INFO - Successfully remapped styles to match Elite HUD
2021-01-12T01:45:53.802Z - EDScoutWebUI-EDScout - INFO - Background thread launched and awaiting data..
2021-01-12T01:45:53.815Z - EDScoutCore-EDScout - INFO - Reporting: {"timestamp": "2021-01-12T01:43:23Z", "event": "NavRoute", "Route": [{"StarSystem": "HIP 31655", "SystemAddress": 1281804470619, "StarPos": [48.28125, 3.53125, -110.75], "StarClass": "G"}, {"StarSystem": "BD+05 1295", "SystemAddress": 2557820801730, "StarPos": [50.34375, -1.9375, -101.78125], "StarClass": "K"}, {"StarSystem": "Trianguli Sector BQ-Y c11", "SystemAddress": 3107576615618, "StarPos": [51.5625, -3.8125, -100.5625], "StarClass": "K"}, {"StarSystem": "LTT 2545", "SystemAddress": 319731796323, "StarPos": [56.28125, -10.90625, -93.3125], "StarClass": "F"}, {"StarSystem": "Urabey", "SystemAddress": 4756911166146, "StarPos": [64.09375, -18.71875, -86.28125], "StarClass": "K"}, {"StarSystem": "Trianguli Sector HM-V b2-7", "SystemAddress": 16064922527113, "StarPos": [70.8125, -21.90625, -80.5625], "StarClass": "M"}, {"StarSystem": "Trianguli Sector MN-S a4-2", "SystemAddress": 40558986677008, "StarPos": [72.84375, -30.0, -79.96875], "StarClass": "T"}, {"StarSystem": "Trianguli Sector RT-Q a5-0", "SystemAddress": 5375688330008, "StarPos": [77.78125, -33.03125, -72.125], "StarClass": "T"}, {"StarSystem": "Trianguli Sector RT-Q a5-2", "SystemAddress": 40560060418840, "StarPos": [83.375, -34.90625, -67.0], "StarClass": "L"}, {"StarSystem": "Trianguli Sector XU-O a6-3", "SystemAddress": 58152246332192, "StarPos": [83.46875, -39.09375, -64.5], "StarClass": "L"}, {"StarSystem": "Kanandos", "SystemAddress": 3652626401635, "StarPos": [84.28125, -45.0625, -62.0625], "StarClass": "F"}, {"StarSystem": "Trianguli Sector QI-T b3-7", "SystemAddress": 16065190831505, "StarPos": [87.09375, -48.5, -59.375], "StarClass": "M"}, {"StarSystem": "Trianguli Sector QI-T b3-4", "SystemAddress": 9468121064849, "StarPos": [86.0625, -55.71875, -54.65625], "StarClass": "TTS"}, {"StarSystem": "LTT 2262", "SystemAddress": 1281804454243, "StarPos": [85.03125, -61.28125, -52.8125], "StarClass": "G"}, {"StarSystem": "Wira", "SystemAddress": 5070074488209, "StarPos": [87.34375, -65.0625, -52.3125], "StarClass": "M"}, {"StarSystem": "Hyades Sector RT-H b10-3", "SystemAddress": 7269097743761, "StarPos": [90.90625, -76.4375, -51.28125], "StarClass": "L"}, {"StarSystem": "Votaroi", "SystemAddress": 2871319668121, "StarPos": [97.84375, -77.09375, -42.0], "StarClass": "M"}, {"StarSystem": "ICZ YO-A c12", "SystemAddress": 3382588674762, "StarPos": [98.34375, -81.25, -32.25], "StarClass": "K"}, {"StarSystem": "HIP 22006", "SystemAddress": 10510911843, "StarPos": [100.5625, -89.34375, -27.75], "StarClass": "F"}, {"StarSystem": "Kongan", "SystemAddress": 13866435880353, "StarPos": [101.8125, -94.125, -16.75], "StarClass": "M"}, {"StarSystem": "Kamadhenu", "SystemAddress": 5031856116434, "StarPos": [110.0, -99.96875, -13.375], "StarClass": "K"}], "type": "NewRoute"}
2021-01-12T01:49:42.319Z - EDScoutCore-EDScout - INFO - Reporting: {"timestamp": "2021-01-12T01:49:43Z", "event": "ReservoirReplenished", "FuelMain": 2.829922, "FuelReservoir": 0.36, "type": "JournalEntry"}

Running current update of windows and chrome. I run on a laptop and frequently allow the machine to hibernate or sleep while ED Scout is running.
One thing noteworthy is that I run multiple profiles/users on chrome with different themes. Occasionally on a fresh startup of my computer  ED Scout launches two windows, one that looks like the normal GUI and has the colors for my primary chrome theme (which gets stuck at "WAITING FOR NAV DATA...") and another that has a black screen which has a status message in the bottom corner "Downloading proxy script..." It doesn't seem to do anything And the colors on the window border correspond with my secondary chrome user, different from the theme on the "GUI" window. 

You have a great program, thanks for releasing it.

**Comment by joncage** [comment]
That log file looks very useful. That's an error communicating with EDSm by the looks of things. It probably needs some cleaner handling in the case that it's struggling to communicate with EDSM I think.

Thanks!

**Comment by KingGLEB** [comment]
EDSM not work and EDScount not work.

**Comment by joncage** [comment]
![Screenshot_20210112-111215_Chrome](https://user-images.githubusercontent.com/73681/104309640-63d59200-54ca-11eb-8a42-7c9319cbd637.jpg)

Looks like EDSM is down at the moment.

**Comment by KingGLEB** [comment]
Can I make the program write that information from the site is not available so that the program does not hang?

**Comment by KingGLEB** [comment]
" We will conduct some maintenance starting today and shut down our current server. Some services will take some weeks to be up to date to new versions that hopefully will help improve some things. No ETA on migration time "
WEEKS :((

**Comment by tautomer** [comment]
> Can I make the program write that information from the site is not available so that the program does not hang?

 I think it's better this way.



> " We will conduct some maintenance starting today and shut down our current server. Some services will take some weeks to be up to date to new versions that hopefully will help improve some things. No ETA on migration time "
> WEEKS :((

[And good news here!](https://twitter.com/edsm_net/status/1349034634559049729?s=21) The website itself should be back tomorrow.
