### ISSUE TITLE
ERROR - Failed to interpret HUD overrides

### ISSUE THREAD

**Issue by EoD** [joncage/ed-scout#144]
When I try to start EDScout, I end up seeing those errors in the logs:
```log
2020-11-20T02:55:55.445Z - EDScoutWebUI-EDScout - ERROR - Failed to interpret HUD overrides; Please check your file is of the format described in https://arkku.com/elite/hud_editor/
2020-11-20T02:55:55.445Z - EDScoutWebUI-EDScout - ERROR - mismatched tag: line 10, column 3
Traceback (most recent call last):
  File "EDScoutWebUI\EDScout.py", line 222, in remap_css_to_match_hud
  File "EDScoutWebUI\HudColourAdjuster.py", line 14, in get_matrix_values
  File "xml\etree\ElementTree.py", line 1197, in parse
  File "xml\etree\ElementTree.py", line 598, in parse
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 10, column 3
```

My override file contains the following parameters:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<GraphicsConfig>
  <GalaxyMap>
		<LocalisationName>$QUALITY_HIGH;</LocalisationName>
		<NebulasCount>300</NebulasCount>
		<MilkywayInstancesBrightness>0.1</MilkywayInstancesBrightness>
		<MilkywayInstancesSize>0.3</MilkywayInstancesSize>
		<StarInstanceCount>40000</StarInstanceCount>
	</High>
  </GalaxyMap>
</GraphicsConfig>
```

Should I worry about that error?

**Comment by joncage** [comment]
I think if you remove that `</High>` tag, the error will go away.

**Comment by EoD** [comment]
Oh, I see the problem. Adding a `<High>` fixed this.

**Comment by joncage** [comment]
That would work too 👍
