### ISSUE TITLE
No data is shown

### ISSUE THREAD

**Issue by brandstaetter** [joncage/ed-scout#159]
Log shown no errors, but no nav data is updated.
Diagnostic build shows:

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "EDScoutWebUI\EDScout.py", line 173, in receive_and_forward
  File "EDScoutCore\EDScout.py", line 47, in trigger_current_journal_check
  File "EDScoutCore\JournalInterface.py", line 189, in trigger_current_journal_check
  File "EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
  File "EDScoutCore\EDScout.py", line 168, in on_journal_change
  File "EDScoutCore\EDScout.py", line 174, in process_new_journal_entries
  File "EDScoutCore\EDScout.py", line 143, in process_journal_change
  File "EDScoutCore\EDScout.py", line 204, in on_new_route
  File "EDScoutCore\EDScout.py", line 181, in get_edsm_system_report
  File "EDScoutCore\EDSMInterface.py", line 72, in get_system_estimated_value
TypeError: exceptions must derive from BaseException
`

**Comment by Kepas-Beleglorn** [comment]
relates to #156

**Comment by joncage** [comment]
Looks like EDSM was having issues. The next release will sort this by displaying an error instead.
