### ISSUE TITLE
EDScout 1.8.2 crashes at startup .Windows 10 Pro

### ISSUE THREAD

**Issue by cyvan** [joncage/ed-scout#177]
Error log:
D:\Archives\Games\EDScout>EDScout.exe
Traceback (most recent call last):
  File "dns\name.py", line 149, in encode
  File "c:\python37\lib\encodings\idna.py", line 76, in ToASCII
  File "c:\python37\lib\encodings\idna.py", line 38, in nameprep
UnicodeError: Invalid character '\uedc1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EDScoutWebUI\EDScout.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "flask_socketio\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "socketio\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "socketio\zmq_manager.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\convenience.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\green\socket.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\support\greendns.py", line 399, in <module>
  File "eventlet\support\greendns.py", line 313, in __init__
  File "eventlet\support\greendns.py", line 316, in clear
  File "dns\resolver.py", line 543, in __init__
  File "dns\resolver.py", line 702, in read_registry
  File "dns\resolver.py", line 682, in _config_win32_fromkey
  File "dns\resolver.py", line 648, in _config_win32_search
  File "dns\name.py", line 889, in from_text
  File "dns\name.py", line 853, in from_unicode
  File "dns\name.py", line 151, in encode
dns.name.LabelTooLong: A DNS label is > 63 octets long.
[20132] Failed to execute script EDScout

**Comment by joncage** [comment]
What options did you launch it with? That's an odd error.

Does running the diangostic build shed any more light?

**Comment by cyvan** [comment]
Sorry I missed this.  I just started it right after install. Ididn't
specify any startup params.

Also the text in my ticket is from the diagnostic build

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by joncage** [comment]
Sounds like this might be a solved issue with a newer version of the python DNS library.

https://github.com/rthalley/dnspython/issues/257

I'll see if I can get that upgraded.

**Comment by cyvan** [comment]
hey Jon,

did you ever get this sorted out?  I downloaded the latest version and its
still happening.  Was just about to go on an extended exploration trip too
:(

**Comment by joncage** [comment]
Try 1.9.0 if it's not _massively_ too late :P

**Comment by cyvan** [comment]
hahah .. just a tad :P
Haven't played ED seriously in years. Poked my head in during the Earth
invasion and to see if my FC was paid up but that was it.
