### ISSUE TITLE
First Time User; No GUI; Diagnostic Build "FileNotFoundError"

### ISSUE THREAD

**Issue by alphasig271** [joncage/ed-scout#185]
Hi,

I am lost in how to bring EDScout to run, meaning to show the GUI.

I've Google Chrome installed and PyCharm Community 2020.1.2.

When installing EDScout using the "Setup-EdScout-1.8.2.0.exe" and run the installed exe, nothing happened.

When installing the Diagnostic Build I get following error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "flaskwebgui.py", line 206, in open_browser
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

The Logfile:
2021-04-18T21:01:51.342Z - EDScoutWebUI-EDScout - INFO - ED Scout v1.8.2 Starting
2021-04-18T21:01:51.857Z - EDScoutWebUI-EDScout - INFO - Looking for HUD overrides in C:\Users\xxxx\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\GraphicsConfigurationOverride.xml
2021-04-18T21:01:51.858Z - EDScoutWebUI-EDScout - INFO - Successfully remapped styles to match Elite HUD

When I'm creating a route in Galaxy Map, there are then route data entries in the log file and they seem "normal" to me.

What I'm doing wrong?

Thx in advance!

Regards,
Andreas

**Comment by joncage** [comment]
You don't need PyCharm installed to run EDScout.

Looks to me like EDscout is failing to find your Chrome browser. Someone had a problem like this before and IIRC they solved it by uninstalling then reinstalling chrome.

**Comment by alphasig271** [comment]
Hi,

Thx for your reply.

I didn't install PyCharm for EDScout. It's installed because my son need for learning Python and I just wanted to mention it.

Yes, uninstalling and reinstalling chrome solved this issue. 

Thx again!

**Comment by joncage** [comment]
No worries. Should be no problem running pycharm on the same system. I do the same 😊
