### ISSUE TITLE
EDScout 1.5 won't start

### ISSUE THREAD

**Issue by raycelander** [joncage/ed-scout#77]
I got this error message:

![EdScout_err](https://user-images.githubusercontent.com/12814766/92087304-9f997600-edcb-11ea-9421-ec500c2270ce.png)

**Comment by joncage** [comment]
That'll teach me not to run the packaged version and double-check it runs okay.

Looks like the installer isn't finding one of the modules I added to do keyboard input:

```
Traceback (most recent call last):
  File "EDScoutWebUI\EDScout.py", line 21, in <module>
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "EDScoutWebUI\WindowToggler.py", line 3, in <module>
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pynput\__init__.py", line 40, in <module>
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pynput\keyboard\__init__.py", line 31, in <module>
  File "pynput\_util\__init__.py", line 82, in backend
ImportError
[24616] Failed to execute script EDScout
```

**Comment by joncage** [comment]
Try this: https://github.com/joncage/ed-scout/releases/tag/v1.5.1

**Comment by raycelander** [comment]
Perfect! v1.5.1 starts now. I will test it today!
Thank you for your outstanding work!

**Comment by joncage** [comment]
o7

**Comment by Rhaedas** [comment]
I was going to report this, but figured it might just be me again, and also got bogged down with other stuff. I'll get it running later and check it out.

When are you planning to update the Git page with newer pictures, or is there more in the pipeline you want to do first?

Doing an excellent development job.

**Comment by joncage** [comment]
Yep, fair point on the pictures. Needs a refresh. I need to play with some automation of the tests I think first and I can use them to automate screen shots potentially.

That will also run a test that should ensure the packaging worked before you excellent commanders run it and point out I broke it again 😉

**Comment by joncage** [comment]
Updated the description image to explain the terminology. There's a couple of others that need an update too.

**Comment by Ketris** [comment]
Version 1.5.1 does the same thing on Windows 10 build 20206.1000

Program will not launch.
![image](https://user-images.githubusercontent.com/726660/93685672-a33d2600-fa76-11ea-8744-2e2b2535c031.png)

**Comment by joncage** [comment]
> Version 1.5.1 does the same thing on Windows 10 build 20206.1000
> 
> Program will not launch.

If you're able, can you try using the diagnostic build? (Extract it then call 'runit.bat'). That should give us a clearer idea what's going wrong so I can put it right 👌🏻

**Comment by Ketris** [comment]
```
E:\dstru\Downloads\EDScout-DiagnosticBuild\EDScout>EDScout.exe
Traceback (most recent call last):
  File "EDScoutWebUI\EDScout.py", line 217, in <module>
  File "EDScoutCore\EDScout.py", line 29, in __init__
  File "EDScoutCore\JournalInterface.py", line 168, in __init__
  File "EDScoutCore\JournalInterface.py", line 197, in _configure_watchers
Exception: Unable to start watching; Path does not exist: C:\Users\dstru\Saved Games/Frontier Developments/Elite Dangerous
[19600] Failed to execute script EDScout
```
The error is correct -- that path does not exist. My saved games are stored at E:\dstru\Saved Games using the standard Windows method of relocating user folders 
![image](https://user-images.githubusercontent.com/726660/93689009-1f903300-fa90-11ea-8daa-272817f57627.png)

This is the first application I've encountered with issues following the redirect and have been using this feature since Windows Vista.

**Comment by joncage** [comment]
Gotcha! Probably a naive assumption I made somewhere along the way. I'll set up a test to replicate your setup and find a fix on Sunday when I'm back at my desk. Should be a fairly simple one I suspect.

Cheers for the help debugging!
