### ISSUE TITLE
EDSM http-502 errors crash EDScout

### ISSUE THREAD

**Issue by joncage** [joncage/ed-scout#81]
Looks like their API might be down and it's causing crashes: 

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python37-32\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Jon/Documents/EDScout/EDScoutWebUI/EDScout.py", line 146, in receive_and_forward
    scout.trigger_current_journal_check()
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 48, in trigger_current_journal_check
    self.journalWatcher.trigger_current_journal_check()
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\JournalInterface.py", line 189, in trigger_current_journal_check
    self._on_journal_change(self.latest_journal)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
    self.report_journal_change(altered_file)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 169, in on_journal_change
    self.process_new_journal_entries(entries_with_populated_nav_route)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 175, in process_new_journal_entries
    self.process_journal_change(new_entry)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 153, in process_journal_change
    self.report_new_info(EDScout.create_system_report(new_entry))
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 94, in create_system_report
    system = EDSMInterface.get_system(system_name)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDSMInterface.py", line 34, in get_system
    raise Exception("request returned bad response code %d" % (data.status_code))
Exception: request returned bad response code 502
```

**Comment by joncage** [comment]
Another slightly different failure:

```
Traceback (most recent call last):
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x05F6CD50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.edsm.net', port=443): Max retries exceeded with url: /api-system-v1/estimated-value?systemName=Swoiphs+PO-O+d7-63 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05F6CD50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\watchdog\observers\api.py", line 203, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\watchdog\observers\api.py", line 376, in dispatch_events
    handler.dispatch(event)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\watchdog\events.py", line 452, in dispatch
    super(PatternMatchingEventHandler, self).dispatch(event)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\watchdog\events.py", line 336, in dispatch
    }[event.event_type](event)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\JournalInterface.py", line 144, in on_modified
    self.on_journal_change(changed_file)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
    self.report_journal_change(altered_file)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 173, in on_journal_change
    self.process_new_journal_entries(entries_with_populated_nav_route)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 179, in process_new_journal_entries
    self.process_journal_change(new_entry)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 148, in process_journal_change
    self.on_new_route(new_entry)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 213, in on_new_route
    report_content = EDScout.get_edsm_system_report(jump_dest['StarSystem'], 'NavRoute')
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDScout.py", line 187, in get_edsm_system_report
    estimated_value = EDSMInterface.get_system_estimated_value(star_system)
  File "C:\Users\Jon\Documents\EDScout\EDScoutCore\EDSMInterface.py", line 73, in get_system_estimated_value
    data = requests.get("https://www.edsm.net/api-system-v1/estimated-value", requestData, headers=headers)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests_cache\core.py", line 136, in request
    **kwargs
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests_cache\core.py", line 109, in send
    return send_request_and_cache_response()
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests_cache\core.py", line 97, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Jon\.virtualenvs\EDScout-yEs4E1p6\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.edsm.net', port=443): Max retries exceeded with url: /api-system-v1/estimated-value?systemName=Swoiphs+PO-O+d7-63 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05F6CD50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```

**Comment by joncage** [comment]
There was a pull request with some suggested changes for his here: https://github.com/joncage/ed-scout/pull/160
